### ISSUE TITLE
그룹 생성하기

### ISSUE THREAD

**Issue by taew0o** [Codeit-Project-MJU-Team1/BackEnd#2]
## ✨ 만들고자 하는 기능
그룹 생성하기

## ✨구현 내용
- [x] prisma Group 모델 생성
- [x] 그룹 data seeding
- [x] route 생성
- [x] api test

## ✨ 예상 기간
8월 12일 ~ 8월 13일

**Comment by Zoonhyeong** [comment]
GOOD
